# Generated by Django 3.2.9 on 2021-11-12 17:11

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20211109_0014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='activation_key_expires',
            field=models.DateTimeField(default=users.models.get_elapse),
        ),
    ]
