# Generated by Django 3.2.9 on 2021-11-15 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'M'), ('W', 'Ж'), ('X', 'Х')], max_length=1, verbose_name='пол'),
        ),
    ]
